config/routes.rb
Rails.application.routes.draw do
  resources :calendar_events do
    collection do
      get :token
      get :microsoft_token
    end
  end
  resources :tenants
  resources :involvements
  resources :roles
  resources :packages
  resources :documents
  resources :landlords do
    collection do
      post :fabricate
    end
  end
  resources :commissions do
    collection do
      get :add_tenant_to
      post :fabricate
      get :prune
    end
    member do
      put :submit
      put :follow_up
    end
  end
  resources :assists
  resources :agents
  resources :deals do
    collection do
      post :fabricate
      get :prune
    end
    member do
      get :pick_status_of
    end
  end
  root :to => 'home#landing'
  devise_for :avatars#, :controllers => { :omniauth_callbacks => 'avatars/omniauth_callbacks' }
  resources :avatars, :only => [:index, :show, :edit, :update] do
    member do
      put :activate
      put :deactivate
    end
  end
  resources :apartments
  resources :social_accounts
  resources :emails
  resources :phones
  resources :niches
  resources :industries
  resources :employments
  resources :employers
  resources :leases
  resources :registrants
  resources :clients
  resources :referral_sources
  resources :registrations do
    member do
      get :display
      get :card
    end
    collection do
      post :fabricate
    end
  end
  get '/register' => 'home#registration', :as => 'begin_registration'
  get '/registrant_add' => 'home#registrant_add', :as => 'registrant_add'
  post '/register' => 'home#submit', :as => 'submit_registration'
  get '/toggle_navigation' => 'home#toggle_navigation', :as => 'toggle_navigation'
  get '/thanks' => 'home#thanks', :as => 'thanks'
end

app/models/social_account.rb
class SocialAccount < ApplicationRecord
  belongs_to :client, :optional => true
  belongs_to :employer, :optional => true
  
  def name
    moniker
  end
end

app/controllers/social_accounts_controller.rb
class SocialAccountsController < ApplicationController
  before_action :set_social_account, only: [:show, :edit, :update, :destroy]

  def index
    @social_accounts = case params[:filtered_attribute]
    when 'industry_id'
      Industry.find(params[:filter_value]).social_accounts
    when nil
      SocialAccount.all
    else
      SocialAccount.where params[:filtered_attribute] => params[:filter_value]
    end.page params[:page]
  end

  def show
  end

  def new
    @social_account = SocialAccount.new
  end

  def edit
  end

  def create
    @social_account = SocialAccount.new(social_account_params)

    respond_to do |format|
      if @social_account.save
        format.html { redirect_to @social_account, notice: 'Social account was successfully created.' }
        format.json { render :show, status: :created, location: @social_account }
      else
        format.html { render :new }
        format.json { render json: @social_account.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @social_account.update(social_account_params)
        format.html { redirect_to @social_account, notice: 'Social account was successfully updated.' }
        format.json { render :show, status: :ok, location: @social_account }
      else
        format.html { render :edit }
        format.json { render json: @social_account.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @social_account.destroy
    respond_to do |format|
      format.html { redirect_to social_accounts_url, notice: 'Social account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_social_account
      @social_account = SocialAccount.find(params[:id])
    end

    def social_account_params
      params.require(:social_account).permit(:variety, :url, :moniker, :client_id, :employer_id)
    end
end

app/helpers/social_accounts_helper.rb
module SocialAccountsHelper
end

app/views/social_accounts/_form.html.erb
<%= form_with(model: social_account, local: true) do |form| %>
  <% if social_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(social_account.errors.count, "error") %> prohibited this social_account from being saved:</h2>

      <ul>
      <% social_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :variety %>
    <%= form.text_field :variety %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :moniker %>
    <%= form.text_field :moniker %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.select :client_id options_from_collection_for_select(Client.all, :id, :name, social_account.client_id), :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :employer_id %>
    <%= form.select :employer_id, options_from_collection_for_select(Employer.all, :id, :name, social_account.employer_id), :include_blank => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/social_accounts/edit.html.erb
<h1>Editing Social Account</h1>

<%= render 'form', social_account: @social_account %>

<%= link_to 'Show', @social_account %>

app/views/social_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Social Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Variety</th>
      <th>Url</th>
      <th>Moniker</th>
      <th>Client</th>
      <th>Employer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @social_accounts.each do |social_account| %>
      <tr>
        <td><%= social_account.variety %></td>
        <td><%= social_account.url %></td>
        <td><%= social_account.moniker %></td>
        <td><%= link_to_name_with_icon social_account.client %></td>
        <td><%= link_to_name_with_icon social_account.employer %></td>
        <td><%= link_to 'Show', social_account %></td>
        <td><%= link_to fa_icon(:highlighter), edit_social_account_path(social_account), :title => 'Edit' %></td>
        <td><%= link_to fa_icon(:backspace), social_account, method: :delete, data: { confirm: 'Are you sure?' }, :title => 'Delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @social_accounts %>
<br>

<%= link_to 'New Social Account', new_social_account_path %>

app/views/social_accounts/new.html.erb
<h1>New Social Account</h1>

<%= render 'form', social_account: @social_account %>

app/views/social_accounts/show.html.erb
<p>
  <strong>Variety:</strong>
  <%= @social_account.variety %>
</p>

<p>
  <strong>Url:</strong>
  <%= @social_account.url %>
</p>

<p>
  <strong>Moniker:</strong>
  <%= @social_account.moniker %>
</p>

<p>
  <strong>Client:</strong>
  <%= link_to_name_with_icon @social_account.client %>
</p>

<p>
  <strong>Employer:</strong>
  <%= link_to_name_with_icon @social_account.employer %>
</p>

<%= link_to fa_icon(:highlighter), edit_social_account_path(@social_account), :title => 'Edit' %>