config/routes.rb
Rails.application.routes.draw do
  resources :calendar_events do
    collection do
      get :token
      get :microsoft_token
    end
  end
  resources :tenants
  resources :involvements
  resources :roles
  resources :packages
  resources :documents
  resources :landlords do
    collection do
      post :fabricate
    end
  end
  resources :commissions do
    collection do
      get :add_tenant_to
      post :fabricate
      get :prune
    end
    member do
      put :submit
      put :follow_up
    end
  end
  resources :assists
  resources :agents
  resources :deals do
    collection do
      post :fabricate
      get :prune
    end
    member do
      get :pick_status_of
    end
  end
  root :to => 'home#landing'
  devise_for :avatars#, :controllers => { :omniauth_callbacks => 'avatars/omniauth_callbacks' }
  resources :avatars, :only => [:index, :show, :edit, :update] do
    member do
      put :activate
      put :deactivate
    end
  end
  resources :apartments
  resources :social_accounts
  resources :emails
  resources :phones
  resources :niches
  resources :industries
  resources :employments
  resources :employers
  resources :leases
  resources :registrants
  resources :clients
  resources :referral_sources
  resources :registrations do
    member do
      get :display
      get :card
    end
    collection do
      post :fabricate
    end
  end
  get '/register' => 'home#registration', :as => 'begin_registration'
  get '/registrant_add' => 'home#registrant_add', :as => 'registrant_add'
  post '/register' => 'home#submit', :as => 'submit_registration'
  get '/toggle_navigation' => 'home#toggle_navigation', :as => 'toggle_navigation'
  get '/thanks' => 'home#thanks', :as => 'thanks'
end

app/models/registrant.rb
class Registrant < ApplicationRecord
  belongs_to :client
  belongs_to :registration
  
  def name
    "#{client.name} in #{registration.name}"
  end
end

app/controllers/registrants_controller.rb
class RegistrantsController < ApplicationController
  before_action :set_registrant, only: [:show, :edit, :update, :destroy]

  def index
    @registrants = case params[:sort]
    when 'first_name'
      Registrant.joins(:client).order 'clients.first_name'
    when 'last_name'
      Registrant.joins(:client).order 'clients.last_name'
    else
      Registrant.recent
    end.page params[:page]
  end

  def show
  end

  def new
    @registrant = Registrant.new
  end

  def edit
  end

  def create
    @registrant = Registrant.new(registrant_params)

    respond_to do |format|
      if @registrant.save
        format.html { redirect_to @registrant, notice: 'Registrant was successfully created.' }
        format.json { render :show, status: :created, location: @registrant }
      else
        format.html { render :new }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @registrant.update(registrant_params)
        format.html { redirect_to @registrant, notice: 'Registrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @registrant }
      else
        format.html { render :edit }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @registrant.destroy
    respond_to do |format|
      format.html { redirect_to registrants_url, notice: 'Registrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_registrant
      @registrant = Registrant.find(params[:id])
    end

    def registrant_params
      params.require(:registrant).permit(:other_fund_sources, :client_id, :registration_id)
    end
end

app/helpers/registrants_helper.rb
module RegistrantsHelper
end

app/views/registrants/_form.html.erb
<%= form_with(model: registrant, local: true) do |form| %>
  <% if registrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registrant.errors.count, "error") %> prohibited this registrant from being saved:</h2>

      <ul>
      <% registrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :other_fund_sources %>
    <%= form.text_area :other_fund_sources %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.select :client_id, options_from_collection_for_select(Client.all, :id, :name, registrant.client_id) %>
  </div>

  <div class="field">
    <%= form.label :registration_id %>
    <%= form.select :registration_id, options_from_collection_for_select(Registration.all, :id, :name, registrant.registration_id) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registrants/edit.html.erb
<h1>Editing Registrant</h1>

<%= render 'form', registrant: @registrant %>

<%= link_to 'Show', @registrant %>

app/views/registrants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registrants</h1>

<table>
  <thead>
    <tr>
      <th>Other fund sources</th>
      <th><%= link_to 'First', filter_params.merge(:sort => 'first_name') %> <%= link_to 'Last', filter_params.merge(:sort => 'last_name') %></th>
      <th>Registration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registrants.each do |registrant| %>
      <tr>
        <td><%= registrant.other_fund_sources %></td>
        <td><%= link_to_name_with_icon registrant.client %></td>
        <td><%= link_to_name_with_icon registrant.registration %></td>
        <td><%= link_to 'Show', registrant %></td>
        <td><%= link_to fa_icon(:highlighter), edit_registrant_path(registrant), :title => 'Edit' %></td>
        <td><%= link_to fa_icon(:backspace), registrant, method: :delete, data: { confirm: 'Are you sure?' }, :title => 'Delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @registrants %>
<br>

<%= link_to 'New Registrant', new_registrant_path %>

app/views/registrants/new.html.erb
<h1>New Registrant</h1>

<%= render 'form', registrant: @registrant %>

<%= link_to 'Back', registrants_path %>

app/views/registrants/show.html.erb
<p>
  <strong>Other fund sources:</strong>
  <%= @registrant.other_fund_sources %>
</p>

<p>
  <strong>Client:</strong>
  <%= link_to_name_with_icon @registrant.client %>
</p>

<p>
  <strong>Registration:</strong>
  <%= link_to_name_with_icon @registrant.registration %>
</p>

<%= link_to fa_icon(:highlighter), edit_registrant_path(@registrant), :title => 'Edit' %>