config/routes.rb
Rails.application.routes.draw do
  resources :calendar_events do
    collection do
      get :token
      get :microsoft_token
    end
  end
  resources :tenants
  resources :involvements
  resources :roles
  resources :packages
  resources :documents
  resources :landlords do
    collection do
      post :fabricate
    end
  end
  resources :commissions do
    collection do
      get :add_tenant_to
      post :fabricate
      get :prune
    end
    member do
      put :submit
      put :follow_up
    end
  end
  resources :assists
  resources :agents
  resources :deals do
    collection do
      post :fabricate
      get :prune
    end
    member do
      get :pick_status_of
    end
  end
  root :to => 'home#landing'
  devise_for :avatars#, :controllers => { :omniauth_callbacks => 'avatars/omniauth_callbacks' }
  resources :avatars, :only => [:index, :show, :edit, :update] do
    member do
      put :activate
      put :deactivate
    end
  end
  resources :apartments
  resources :social_accounts
  resources :emails
  resources :phones
  resources :niches
  resources :industries
  resources :employments
  resources :employers
  resources :leases
  resources :registrants
  resources :clients
  resources :referral_sources
  resources :registrations do
    member do
      get :display
      get :card
    end
    collection do
      post :fabricate
    end
  end
  get '/register' => 'home#registration', :as => 'begin_registration'
  get '/registrant_add' => 'home#registrant_add', :as => 'registrant_add'
  post '/register' => 'home#submit', :as => 'submit_registration'
  get '/toggle_navigation' => 'home#toggle_navigation', :as => 'toggle_navigation'
  get '/thanks' => 'home#thanks', :as => 'thanks'
end

app/models/deal.rb
include CommissionsHelper
class Deal < ApplicationRecord
  belongs_to :agent
  has_many :assists, :dependent => :destroy
  has_many :agents, -> { distinct }, :through => :assists
  belongs_to :package, :optional => true
  has_one :commission
  has_one :landlord, :through => :commission
  has_one :lease, :through => :commission
  has_many :clients, :through => :lease
  has_many :documents
  delegate :fub_people, :annualized_rent, :agent_split_percentage, :citi_commission, :owner_pay_commission, :tenant_side_commission, :listing_side_commission, :total_commission,
           :co_broke_commission, :citi_habitats_referral_agent_amount, :corcoran_referral_agent_amount, :outside_agency_amount, :relocation_referral_amount, :lease_end_date,
           :lease_sign_date, :lease_start_date, :lease_term, :leased_monthly_rent, :property_address, :apartment_number, :to => :commission, :allow_nil => true
  
  enum :status => [:preliminary, :underway, :submitted, :approved, :accepted, :rejected, :withdrawn, :cancelled, :closed, :commission_requested, :commission_processed]
  attr_default :status, :preliminary
  
  scope :this_week, -> { where Deal.arel_table[:created_at].gt 1.week.ago }

  def reference
    if name.present?
      name
    else
      "#{address} #{unit_number}"
    end
  end
  
  def subcommissions
    package = Hash.new 0
    assists.each do |assist|
      package[assist.agent.payable_name] += assist.payout
    end
    
    package[agent.name] += agent_commission
    package
  end
  
  def inbound_commission
    citi_commission.to_d - listing_side_commission.to_d
  end
  
  def remaining_commission
    inbound_commission - internal_referral
  end
  
  def closeout
    agent_split_percentage.percent_of remaining_commission
  end
  
  def house_cut
    remaining_commission * (1 - (agent_split_percentage.to_d / BigDecimal(100)))
  end
  
  def agent_commission
    remaining_commission * (agent_split_percentage.to_d / BigDecimal(100)) - distributed_commission
  end
  
  def company_commission
    20.percent_of(remaining_commission) - special_payments_total rescue nil
  end
  
  def payout_to assisting_agent
    assists.where(:agent => assisting_agent).sum &:payout if commission
  end
  
  def roles_for assisting_agent
    assists.where(:agent => assisting_agent).map(&:name).to_sentence
  end
  
  def distributable_commission participation_rate
    participation_rate.percent_of(remaining_commission - expenses)
  end
  
  def distributed_commission
    assists.inject(0) { |sum, assist| sum + assist.payout.to_d }
  end
  
  def expenses
    assists.sum :expense
  end
  
  def referral_payment
    listing_fee.to_d + citi_habitats_referral_agent_amount.to_d + corcoran_referral_agent_amount.to_d + outside_agency_amount.to_d + relocation_referral_amount.to_d
  end
  
  def external_referral
    corcoran_referral_agent_amount.to_d + outside_agency_amount.to_d + relocation_referral_amount.to_d
  end
  
  def internal_referral
    listing_fee.to_d + citi_habitats_referral_agent_amount.to_d
  end
  
  def listing_fee
    (commission.listing_fee_percentage / BigDecimal(100)) * inbound_commission if commission&.listing_fee?
  end
  
  def staffed?
    assists.leading.present? && assists.interviewing.present? && assists.showing.present? && assists.closing.present?
  end
  
  def unit_type
    case commission.bedrooms
    when 0
      'Studio'
    else
      "#{rounded commission.bedrooms} Bedroom"
    end
  end
  
  def fub_deal
    @fub_deal ||= FubClient::Deal.find(follow_up_boss_id) || fub_create
  end
  
  def fub_create
    agents.each do |agent|
      fub_object = FubClient::Deal.new(:name => "#{property_address} ##{apartment_number}", :stageId => ENV['FOLLOW_UP_BOSS_STAGE_ID_CLOSED'],
        :price => leased_monthly_rent, :commissionValue => payout_to(agent), :projectedCloseDate => lease_sign_date, :description => fub_description(roles_for(agent)),
        :peopleIds => fub_people.map(&:id).append(landlord.follow_up_boss_id), :userIds => [agent.follow_up_boss_id])
      begin
        fub_object.save
      rescue NoMethodError => error
        Rails.logger.debug error.inspect
      end
    end
    fub_object = FubClient::Deal.new(:name => "#{property_address} ##{apartment_number}", :stageId => ENV['FOLLOW_UP_BOSS_STAGE_ID_CLOSED'],
      :price => leased_monthly_rent, :commissionValue => total_commission, :projectedCloseDate => lease_sign_date, :description => fub_description,
      :peopleIds => fub_people.map(&:id).append(landlord.follow_up_boss_id), :userIds => [agent.follow_up_boss_id])
    begin
      fub_object.save
    rescue NoMethodError => error
      Rails.logger.debug error.inspect
    end
    update_attribute :follow_up_boss_id, fub_object.id
    fub_object
  end
  
  def fub_annotate_people
    clients.each do |client|
      fub_note = FubClient::Note.new :subject => 'Closing', :body => 'We rented them an apartment.', :personId => client.follow_up_boss_id
      begin
        fub_note.save
      rescue NoMethodError => error
        Rails.logger.debug error.inspect
      end
    end
  end
  
  def fub_description with_roles = ''
    <<~DESCRIBE
    #{clients.map(&:name).to_sentence}
    Address: #{address} ##{unit_number}
    Apt Type: #{unit_type}
    Lease Start: #{lease_start_date.strftime("%b ") + lease_start_date.day.ordinalize + ", " + lease_start_date.year.to_s}
    Lease Term: #{lease_term}
    Rent: #{rounded leased_monthly_rent}
    Commission: #{rounded total_commission}#{owner_pay_commission.present? ? "\nOwner Pay Commission: #{rounded owner_pay_commission}" : ''}
    Landlord: #{landlord.name}
    #{with_roles}
    DESCRIBE
  end
  
  def special_efforts
    assists.group_by(&:agent_id).select do |agent_id, assists|
      assists.reject(&:new_record?).inject(0) { |sum, assist| sum + assist.role_rate } > 0.45
    end
  end
  
  def special_payments
    special_efforts.map do |agent_id, assists|
      assisting_agent = Agent.find agent_id
      if agents.map(&:name).append(agent.name).include? assisting_agent.distinct_payable_name
        "Override payment from #{assisting_agent.payable_name} to #{assisting_agent.name}: #{number_to_currency 10.percent_of remaining_commission}"
      end
    end
  end
  
  def special_payments_total
    special_payments.compact.count * 10.percent_of(remaining_commission)
  end
  
  def rate_for role
    send "#{role}_rate"
  end
  
  def lead_rate
    0.20
  end
  
  def interview_rate
    0.25
  end
  
  def show_rate
    0.30
  end
  
  def close_rate
    0.25
  end
  
  def custom_rate
    0
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :pick_status_of, :update, :destroy]

  def index
    @deals = case params[:filtered_attribute]
    when 'agent_id'
      Deal.where :agent_id => params[:filter_value]
    when nil
      Deal.all
    else
      Deal.where params[:filtered_attribute] => params[:filter_value]
    end
    @deals = case params[:sort]
    when 'commission'
      @deals.joins(:commission).order 'commissions.total_commission desc nulls last'
    when 'agent'
      @deals.order 'agent_id'
    when 'address'
      @deals.order 'address nulls last'
    when 'unit_number'
      @deals.order 'unit_number nulls last'
    when 'status'
      @deals.order :status
    when 'updated_at'
      @deals.order 'updated_at desc'
    else
      @deals
    end.page params[:page]
  end

  def show
    @title = @deal.reference
  end

  def new
    @deal = Deal.new :agent => Agent.where(:first_name => ENV['SENIOR_AGENT_FIRST_NAME']).take
  end

  def edit
  end
  
  def pick_status_of
  end

  def create
    @deal = Deal.new deal_params
    @deal.agent = Agent.where(:first_name => ENV['SENIOR_AGENT_FIRST_NAME']).take

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @deal.update deal_params
        format.js
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @deal.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def fabricate
    @agent = Agent.where(:id => params[:deal][:agent_id]).take || Agent.where(:first_name => ENV['SENIOR_AGENT_FIRST_NAME']).take
    @deal = case params[:deal][:status]
    when 'underway'
      Fabricate :underway_deal, :agent => @agent
    when 'completed'
      Fabricate :completed_deal, :agent => @agent
    end
  end

  private
    def set_deal
      @deal = Deal.find params[:id]
    end

    def deal_params
      params.require(:deal).permit :name, :address, :unit_number, :status, :commission, :package_id
    end
end

app/helpers/deals_helper.rb
module DealsHelper
  def assist_adder deal
    form_with :model => deal.assists.new, :id => 'assist_adder' do |form|
      form.select(:role_id, options_from_collection_for_select(Role.all, :id, :name)) +
      form.select(:agent_id, options_from_collection_for_select(Agent.recent.active, :id, :name) + (add_name_option)) +
      form.submit(:add) +
      form.hidden_field(:deal_id)
    end
  end
  
  def add_name_option
    content_tag :option, 'Add Name', :id => 'add_name_option', :value => 'Add Name'
  end
  
  def status_clicker_for deal
    div_for deal, :status_clicker_for do
      link_to deal.status, pick_status_of_deal_path(deal), :remote => true
    end
  end
  
  def status_picker_for deal
    div_for deal, :status_picker_for do
      select_tag :status, options_for_select(Deal.statuses.keys, deal.status)
    end
  end
  
  def deal_row_for deal
    columns = [
      content_tag(:td, link_to_name_with_icon(deal, :reference)),
      content_tag(:td, number_to_currency(deal.commission&.total_commission)),
      content_tag(:td, link_to_name_with_icon(deal.agent)),
      content_tag(:td, deal.address),
      content_tag(:td, deal.unit_number),
      content_tag(:td, status_clicker_for(deal)),
      content_tag(:td, deal.updated_at&.to_s(:descriptive)),
      content_tag(:td, link_to(fa_icon(:file_invoice_dollar, :size => '2x'), deal, :title => 'Finance Breakdown')),
      content_tag(:td, link_to(fa_icon(:atlas, :size => '2x'), edit_deal_path(deal), :title => 'Manage Deal Details')),
      content_tag(:td, link_to(fa_icon(:file_signature, :size => '2x'), new_document_path(:document => {:deal_id => deal}), :title => 'Attach Document'))
    ]
    
    if deal.commission
      columns << content_tag(:td, link_to(fa_icon(:newspaper, :size => '2x'), edit_commission_path(deal.commission), :title => 'Update Paperwork'))
      columns << content_tag(:td, link_to(fa_icon(:file_export, :size => '2x'), commission_path(deal.commission, :format => :pdf), :title => 'Print Preview of Rental Request for Commission'))
    else
      columns << content_tag(:td, link_to(fa_icon(:newspaper, :size => '2x'), new_commission_path(:deal_id => deal.id), :title => 'Begin Paperwork'))
      columns << tag.td
    end
    
    if deal.documents.present?
      columns << content_tag(:td, link_to(fa_icon(:hdd, :text => "(#{deal.documents.count})", :size => '2x'), documents_path(filter_params deal), :title => pluralize(deal.documents.count, 'Uploaded Document')), :class => 'document_list')
    else
      columns << content_tag(:td, link_to(fa_icon(:hdd, :size => '2x'), documents_path, :title => pluralize(deal.documents.count, 'Uploaded Document')), :class => 'document_list')
    end
    
    if current_avatar.admin?
      columns << content_tag(:td, link_to(fa_icon(:backspace, :class => 'deletion', :size => '2x'), deal, :title => 'Delete Deal and its Assists', :method => :delete, :remote => true, :data => {:confirm => 'Are you sure?'}), :class => 'deal_removal')
    end
    
    content_tag :tr, columns.join.html_safe, :id => dom_id(deal)
  end
  
  def fabricate_deal_link opts = {}
    if params[:filtered_attribute] == 'agent_id'
      opts[:agent_id] = params[:filter_value]
    end
    link_to "Fabricate #{opts[:status]} deal", fabricate_deals_path(:deal => opts), :method => :post, :remote => true unless Rails.env.production?
  end
  
  def special_payments_on deal
    deal.special_payments.join
  end
end

app/views/deals/_form.html.erb
<%= form_with(model: deal, local: true) do |form| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nickname (optional)' %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :unit_number %><br>
    <%= form.text_field :unit_number %>
  </div>
  
  <div class="field">
    <%= form.label :agent %><br>
    <%= form.select :agent_id, options_from_collection_for_select(Agent.alpha, :id, :name, deal.agent_id) %>
  </div>
  
  <div class="field">
    <%= form.label :package %><br>
    <%= form.select :package_id, options_from_collection_for_select(Package.all, :id, :name, deal.package_id) %>
  </div>
  
  <div class="field">
    <%= form.label :status %><br>
    <%= form.select :status, Deal.statuses.keys, :include_blank => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/deals/destroy.js.erb
$('#<%=j dom_id @deal %>').fadeOut(690);

app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %>

app/views/deals/fabricate.js.erb
$('#deals_table').append('<%=j deal_row_for @deal %>');

app/views/deals/index.html.erb
<h1>Deals</h1>
<header>These are some of the deals that the team is working on.</header>

<table>
  <thead id="deal_control">
    <tr>
      <th>Name</th>
      <th><%= link_to 'Commission', :sort => 'commission', :filter_value => params[:filter_value], :filtered_attribute => params[:filtered_attribute] %></th>
      <th><%= link_to 'Agent', :sort => 'agent', :filter_value => params[:filter_value], :filtered_attribute => params[:filtered_attribute] %></th>
      <th><%= link_to 'Address', :sort => 'address', :filter_value => params[:filter_value], :filtered_attribute => params[:filtered_attribute] %></th>
      <th><%= link_to 'Unit number', :sort => 'unit_number', :filter_value => params[:filter_value], :filtered_attribute => params[:filtered_attribute] %></th>
      <th><%= link_to 'Status', :sort => 'status', :filter_value => params[:filter_value], :filtered_attribute => params[:filtered_attribute] %></th>
      <th><%= link_to 'Updated', :sort => 'updated_at', :filter_value => params[:filter_value], :filtered_attribute => params[:filtered_attribute] %></th>
      <th colspan='5'></th>
      <th><%= link_to 'Prune', prune_deals_path, :remote => true if current_avatar.admin? %></th>
    </tr>
  </thead>

  <tbody id="deals_table">
    <% @deals.each do |deal| %>
      <%= deal_row_for deal %>
    <% end %>
  </tbody>
</table>

<%= paginate @deals %>

<br>

<div class="tools">
  <%= link_to 'New Deal', new_deal_path %>
  <%= fabricate_deal_link :status => :completed %>
  <%= fabricate_deal_link :status => :underway %>
</div>

app/views/deals/new.html.erb
<h1>Input the Deal</h1>

<%= render 'form', deal: @deal %>

app/views/deals/pick_status_of.js.erb
$('#status_clicker_for_deal_<%= @deal.id %>').replaceWith('<%=j status_picker_for @deal %>');
activate_status_picker('<%= @deal.id %>');

app/views/deals/prune.js.erb
$('.deal_removal').slideToggle(1200);

app/views/deals/show.html.erb
<div class="tools">
  <% if @deal.commission %>
    <%= link_to fa_icon(:stream, :size => '2x'), @deal.commission, :title => 'Review Commission Data' if @deal.commission.present? %>
    <%= link_to fa_icon(:file_export, :size => '2x'), commission_path(@deal.commission, :format => :pdf), :title => 'Print Preview of Rental Request for Commission' %>
    <%= link_to fa_icon(:newspaper, :size => '2x'), edit_commission_path(@deal.commission), :title => 'Fill Out Paperwork' %>
  <% else %>
    <%= link_to fa_icon(:newspaper, :size => '2x'), new_commission_path(:deal_id => @deal), :title => 'Begin Paperwork' %>
  <% end %>
  <%= link_to fa_icon(:atlas, :size => '2x'), edit_deal_path(@deal), :title => 'Manage Deal Details' %>
  <%= link_to fa_icon(:file_signature, :size => '2x'), new_document_path(:document => {:deal_id => @deal}), :title => 'Attach Document' %>
</div>

<% if @deal.name.present? %>
  <p>
    <strong>Nickname:</strong>
    <%= @deal.name %>
  </p>
<% end %>
<p>
  <%= @deal.address %>
  <strong><%= @deal.unit_number %></strong>
</p>

<p>
  <strong>Status:</strong>
  <%= @deal.status %>
</p>

<p class="agent">
  Agent: <%= link_to_name_with_icon @deal.agent %>
</p>

<div id="deal_payout_breakdown">
  <div>
    <%= content_tag :div, 'Rent', :class => 'deal_portion_description' %>
    <%= content_tag :div, rounded(@deal.annualized_rent), :class => 'deal_portion' %>
  </div>
  <%= tag.hr %>
  
  <div>
    <%= content_tag :div, 'Tenant Commission', :class => 'deal_portion_description' %>
    <%= content_tag :div, rounded(@deal.tenant_side_commission), :class => 'deal_portion' %>
  </div>
  
  <% if @deal.listing_side_commission > 0 %>
    <div>
      <%= content_tag :div, 'Listing Side Commission', :class => 'deal_portion_description' %>
      <%= content_tag :div, "+ #{rounded @deal.listing_side_commission}", :class => 'deal_portion' %>
    </div>
  <% end %>
  
  <% if @deal.owner_pay_commission > 0 %>
    <div>
      <%= content_tag :div, 'Owner Commission', :class => 'deal_portion_description' %>
      <%= content_tag :div, "+ #{rounded @deal.owner_pay_commission}", :class => 'deal_portion' %>
    </div>
  <% end %>
  
  <div>
    <%= tag.div :class => 'deal_portion_description' %>
    <%= content_tag :div, tag.hr, :class => 'deal_portion' %>
  </div>
  
  <div>
    <%= content_tag :div, 'Total Commission', :class => 'deal_portion_description' %>
    <%= content_tag :div, rounded(@deal.total_commission), :class => 'deal_portion' %>
  </div>
  
  <% if @deal.listing_side_commission > 0 %>
    <div>
      <%= content_tag :div, 'Listing Side', :class => 'deal_portion_description' %>
      <%= content_tag :div, "- #{rounded @deal.listing_side_commission}", :class => 'deal_portion' %>
    </div>
  <% end %>
  
  <% if @deal.co_broke_commission > 0 %>
    <div>
      <%= content_tag :div, 'Co-Broke', :class => 'deal_portion_description' %>
      <%= content_tag :div, "- #{rounded @deal.co_broke_commission}", :class => 'deal_portion' %>
    </div>
  <% end %>
  
  <% if @deal.listing_fee.present? %>
    <div>
      <%= content_tag :div, 'Listing Fee', :class => 'deal_portion_description' %>
      <%= content_tag :div, "#{rounded @deal.listing_fee}", :class => 'deal_portion' %>
    </div>
  <% end %>
  
  <% if @deal.referral_payment > 0 %>
    <div>
      <%= content_tag :div, 'Referral Payment', :class => 'deal_portion_description' %>
      <%= content_tag :div, "- #{rounded @deal.referral_payment}", :class => 'deal_portion' %>
    </div>
  <% end %>
  
  <div>
    <%= tag.div :class => 'deal_portion_description' %>
    <%= content_tag :div, tag.hr, :class => 'deal_portion' %>
  </div>
  
  <div>
    <%= content_tag :div, 'Inbound Commission', :class => 'deal_portion_description' %>
    <%= content_tag :div, rounded(@deal.inbound_commission), :class => 'deal_portion' %>
  </div>
  
  <div>
    <%= content_tag :div, 'Remaining Commission', :class => 'deal_portion_description' %>
    <%= content_tag :div, rounded(@deal.remaining_commission), :class => 'deal_portion' %>
  </div>
  
  <% if current_avatar.admin? %>
    <div>
      <%= content_tag :div, 'Citi Habitats Cut', :class => 'deal_portion_description' %>
      <%= content_tag :div, rounded(@deal.house_cut), :class => 'deal_portion' %>
    </div>
    <div>
      <%= content_tag :div, 'Desmond Closeout', :class => 'deal_portion_description' %>
      <%= content_tag :div, rounded(@deal.closeout), :class => 'deal_portion' %>
    </div>
    
    <div>
      <%= content_tag :div, 'CitiPads Closeout', :class => 'deal_portion_description' %>
      <%= content_tag :div, rounded(@deal.agent_commission), :class => 'deal_portion' %>
    </div>
  <% end %>
  
</div>
<div id="commission_assist_adder">
  <% 
  newVals = [];
  newValsColors = [];
  newValsNames = []; 
	 %>
  <% @deal.assists.chrono.each do |assist| %>
    <%= div_for assist do %>
      <%= content_tag :div, linked_name(assist), :class => 'deal_portion_description' %>
      <% if current_avatar.admin? || assist.agent.avatar == current_avatar %>
        <%= content_tag :div, :class => 'deal_portion' do %>
          <%= rounded @deal.distributable_commission assist.rate %> * <%= assist.role_rate %>
          <%= '+ ' if assist.adjustment.to_d > 0 %>
          <%= rounded assist.adjustment %>
          <%= '+ ' if assist.expense.to_d > 0 %>
          <%= rounded assist.expense %>
          <% if @deal.assists.where(:role => assist.role).count > 1 %>
            / <%= @deal.assists.where(:role => assist.role).count %>
          <% end %>
          = <%= number_to_currency(assist.payout) %>
		  <% newVals << assist.payout;
		  	 newValsNames << assist.name; 
			 newValsColors << "#%06x" % (rand * 0xffffff);
			 %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div style="width: 400px; height: 400px;">
<% pieData = { 
	datasets: [ {
		data: newVals,
		backgroundColor: newValsColors
	}],
	labels: newValsNames
};%>
<%= pie_chart pieData %>
</div>

<% if current_avatar.admin? %>
  <div class="payout">
    <%= @deal.commission&.subcommission_payout_summary %>
  </div>
<% end %>

<%= assist_adder @deal %>

<%= special_payments_on @deal if current_avatar.admin? %>

<div class="document_list">
  <% if @deal.documents.present? %>
    <header>
      <%= pluralize @deal.documents.count, 'Document' %>
    </header>
  <% end %>
  <table>
    <% @deal.documents.each do |document| %>
      <%= div_for document do %>
        <%= document_row_for document %>
      <% end %>
    <% end %>
  </table>
</div>

app/views/deals/update.js.erb
$('#status_picker_for_deal_<%= @deal.id %>').replaceWith('<%=j status_clicker_for @deal %>');