config/routes.rb
Rails.application.routes.draw do
  resources :calendar_events do
    collection do
      get :token
      get :microsoft_token
    end
  end
  resources :tenants
  resources :involvements
  resources :roles
  resources :packages
  resources :documents
  resources :landlords do
    collection do
      post :fabricate
    end
  end
  resources :commissions do
    collection do
      get :add_tenant_to
      post :fabricate
      get :prune
    end
    member do
      put :submit
      put :follow_up
    end
  end
  resources :assists
  resources :agents
  resources :deals do
    collection do
      post :fabricate
      get :prune
    end
    member do
      get :pick_status_of
    end
  end
  root :to => 'home#landing'
  devise_for :avatars#, :controllers => { :omniauth_callbacks => 'avatars/omniauth_callbacks' }
  resources :avatars, :only => [:index, :show, :edit, :update] do
    member do
      put :activate
      put :deactivate
    end
  end
  resources :apartments
  resources :social_accounts
  resources :emails
  resources :phones
  resources :niches
  resources :industries
  resources :employments
  resources :employers
  resources :leases
  resources :registrants
  resources :clients
  resources :referral_sources
  resources :registrations do
    member do
      get :display
      get :card
    end
    collection do
      post :fabricate
    end
  end
  get '/register' => 'home#registration', :as => 'begin_registration'
  get '/registrant_add' => 'home#registrant_add', :as => 'registrant_add'
  post '/register' => 'home#submit', :as => 'submit_registration'
  get '/toggle_navigation' => 'home#toggle_navigation', :as => 'toggle_navigation'
  get '/thanks' => 'home#thanks', :as => 'thanks'
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :registration
  
  def name
    "#{unit_number} #{street_number} #{street_name} [#{ApplicationController.helpers.number_to_round_currency rent} #{size}]"
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  def index
    @apartments = if params[:filtered_attribute]
      Apartment.where params[:filtered_attribute] => params[:filter_value]
    else
      Apartment.all
    end.page params[:page]
  end

  def show
  end

  def new
    @apartment = Apartment.new
  end

  def edit
  end

  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    def apartment_params
      params.require(:apartment).permit(:unit_number, :street_number, :street_name, :zip_code, :size, :rent, :comment, :registration_id)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :unit_number %>
    <%= form.text_field :unit_number %>
  </div>

  <div class="field">
    <%= form.label :street_number %>
    <%= form.text_field :street_number %>
  </div>

  <div class="field">
    <%= form.label :street_name %>
    <%= form.text_field :street_name %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.text_field :rent %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="field">
    <%= form.label :registration_id %>
    <%= form.select :registration_id, options_from_collection_for_select(Registration.all, :id, :name, apartment.registration_id), :include_blank => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Unit number</th>
      <th>Street number</th>
      <th>Street name</th>
      <th>Zip code</th>
      <th>Size</th>
      <th>Rent</th>
      <th>Comment</th>
      <th>Registration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.unit_number %></td>
        <td><%= apartment.street_number %></td>
        <td><%= apartment.street_name %></td>
        <td><%= apartment.zip_code %></td>
        <td><%= apartment.size %></td>
        <td><%= number_to_round_currency apartment.rent %></td>
        <td><%= apartment.comment %></td>
        <td><%= link_to_name_with_icon apartment.registration %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to fa_icon(:highlighter), edit_apartment_path(apartment), :title => 'Edit' %></td>
        <td><%= link_to fa_icon(:backspace), apartment, method: :delete, data: { confirm: 'Are you sure?' }, :title => 'Delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @apartments %>
<br>

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

app/views/apartments/show.html.erb
<p>
  <strong>Unit number:</strong>
  <%= @apartment.unit_number %>
</p>

<p>
  <strong>Street number:</strong>
  <%= @apartment.street_number %>
</p>

<p>
  <strong>Street name:</strong>
  <%= @apartment.street_name %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @apartment.zip_code %>
</p>

<p>
  <strong>Size:</strong>
  <%= @apartment.size %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @apartment.rent %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @apartment.comment %>
</p>

<p>
  <strong>Registration:</strong>
  <%= link_to_name_with_icon @apartment.registration %>
</p>

<%= link_to fa_icon(:highlighter), edit_apartment_path(@apartment), :title => 'Edit' %>